#!/bin/sh

enable(){
    sed -i.bak -z "s#res === null || res === undefined || \!res || res\n\t\t\t.data.status.toLowerCase() \!== 'active'#false#g" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js && systemctl restart pveproxy.service && {
    echo "已屏蔽订阅提示，请在浏览器中按 Ctrl+F5 刷新缓存\n若想还原订阅提示，请执行命令：\nremovepvetip --disable"
    }
}

disable(){
    if [ -f "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js.bak" ];
    then
        mv -f "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js.bak" "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js" && echo "已关闭屏蔽订阅提示"
    else
        echo "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js.bak 不存在，请尝试强制还原\nremovepvetip --force-disable"
    fi
}

forceDisable(){
    apt install --reinstall proxmox-widget-toolkit && echo "已强制还原订阅提示，请在浏览器中按 Ctrl+F5 刷新缓存" || echo "强制还原订阅提示失败，请确认网络已连接"
}

hookRemove(){
    lastUpgradeInfo=`zcat -f $(ls -tr /var/log/apt/history.log*)|awk -v RS= '/.*/{s=$0}; END{print s}'`

    #echo $lastUpgradeInfo

    lastUpgrade=`echo "$lastUpgradeInfo" | grep "proxmox-widget-toolkit"`
    isReinstall=`echo "$lastUpgradeInfo" | grep "^Reinstall"`

    if [ ! -z "$lastUpgrade" -a -z "$isReinstall" ];
    then
        # 上次已更新 proxmox-widget-toolkit，制作屏蔽订阅操作
        nowDate=`date +"%Y-%m-%d %H:%M:%S" | awk -F'[-: ]'  '{printf "%d年%d月%d日 %d时%d分%d秒\n", $1, $2, $3, $4, $5, $6}'`
        echo "$nowDate ：已更新 proxmox-widget-toolkit，执行屏蔽订阅提示操作"
        enable
        echo "若不想每次更新 proxmox-widget-toolkit 后执行屏蔽订阅提示操作，请执行以下命令：\nremovepvetip --unhook"
    fi
}

hook(){
    echo 'DPkg::Post-Invoke {"sh /usr/local/bin/removepvetip --hook-remove"; };' > /etc/apt/apt.conf.d/90removepvetip && echo "已开启 hook，每次更新 proxmox-widget-toolkit 开启屏蔽订阅提示，如需关闭 hook，请执行以下命令：\nremovepvetip --unhook"
}

unhook(){
    rm /etc/apt/apt.conf.d/90removepvetip && echo "已关闭 hook"
}

case "$1" in
"--enable")
    enable
    ;;
"--disable")
    disable
    ;;
"--force-disable")
    forceDisable
    ;;
"--hook-remove")
    hookRemove
    ;;
"--hook")
    hook
    ;;
"--unhook")
    unhook
    ;;
*)
    echo "--enable        开启屏蔽订阅提示"
    echo "--disable       关闭屏蔽订阅提示"
    echo "--force-disable 强制关闭（还原）屏蔽订阅提示，需要联网"
    echo "--hook          开启 hook，每次更新 proxmox-widget-toolkit 开启屏蔽订阅提示"
    echo "--unhook        关闭 hook，每次更新 proxmox-widget-toolkit 不开启屏蔽订阅提示"
    echo "--hook-remove    更新 proxmox-widget-toolkit 调用 hook 参数"
    ;;
esac
